# Generated by Django 5.1.1 on 2024-09-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_author_alter_story_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text="Bağlantı eklemek istediğiniz web sitesinin URL'si.", max_length=500)),
                ('anchor_text', models.CharField(help_text='Bağlantı için kullanılacak metin.', max_length=255)),
                ('quality_score', models.IntegerField(default=0, help_text="Backlink'in kalite skoru (AI tarafından hesaplanabilir).")),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(help_text='Sayfa başlığını girin (SEO için önemli).', max_length=255)),
                ('meta_description', models.TextField(help_text='Meta açıklamaları (Google arama sonuçları için önemli).')),
                ('keywords', models.CharField(help_text='Anahtar kelimeler (virgülle ayırarak).', max_length=255)),
                ('robot_directives', models.TextField(blank=True, help_text='robots.txt ayarları.')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.CharField(blank=True, help_text='SEO anahtar kelimeleri', max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO için meta description'),
        ),
    ]
