# Generated by Django 5.1.1 on 2024-09-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_backlink_seosettings_story_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlink',
            name='anchor_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='backlink',
            name='quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backlink',
            name='target_url',
            field=models.URLField(max_length=500),
        ),
    ]
