# Generated by Django 5.1.1 on 2024-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_badge_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
