# Generated by Django 5.1.1 on 2024-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_alter_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='story_audio/'),
        ),
    ]
